## Environment NODE
version: "3.8"
services:
  environment:
    container_name: ${HOSTNAME}
    hostname: ${HOSTNAME}
    image: ${HOSTNAME}
    labels:
      description: ${HOSTNAME}
      org.opencontainers.image.name: ${HOSTNAME}
      org.opencontainers.image.authors: ${AUTHOR}
      org.opencontainers.image.hostname: ${HOSTNAME}
      com.docker.volume.name: ${HOSTNAME}
      com.docker.network.bridge.name: ${HOSTNAME}
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - DIRECTORY=${VOLUME}
        - ENVIRONMENT=${NODE_ENV}
    volumes:
      - .:${VOLUME}
    env_file:
      - ./.env
    environment:
      NODE_ENV: ${NODE_ENV}
    command: npm run ${NODE_ENV}
    networks:
      - local-network
    restart: always
    ports:
      - ${PORT}:${PORT}
volumes:
  local-volume:
    name: ${HOSTNAME}
networks:
  local-network:
    name: ${HOSTNAME}
    driver: bridge
