# olombongo ms-database: -pot 3307
version: '3.8'
services:
  app:
    container_name: $HOSTNAME
    hostname: $HOSTNAME
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
        - NODE_ENV=$NODE_ENV
        - SECRET_KEY_SALT=$SECRET_KEY_SALT
        - ENDPOINT=$ENDPOINT
        - HOSTNAME=$HOSTNAME
    working_dir: /usr/local/$HOSTNAME
    command: npm run $NODE_ENV
    environment:
      - PORT=$PORT
      - ENDPOINT=$ENDPOINT
      - SECRET_KEY_SALT=$SECRET_KEY_SALT
    volumes:
      - ./:/usr/local/$HOSTNAME
    env_file: ".env"
    networks:
      - default-network
    restart: always
    ports:
      - $PORT:$PORT # host:container   
volumes:
  default-volume:
    name: $HOSTNAME

networks:
  default-network:
    name: $HOSTNAME
    driver: bridge
