# olombongo ms-database: -pot 3307
version: '3.8'

services:

  ms-authentication-mirror:
    container_name: ms-authentication-mirror
    hostname: ms-authentication-mirror
    build:
      context: .
      dockerfile: Dockerfile
      target: ms-authentication-mirror
      args:
        - PORT=$PORT
        - NODE_ENV=$NODE_ENV
        - SECRET_KEY_SALT=$SECRET_KEY_SALT
        - ENDPOINT=$ENDPOINT
    working_dir: /usr/local/ms-authentication-mirror
    command: npm run $NODE_ENV
    environment:
      - PORT=$PORT
      - ENDPOINT=$ENDPOINT
      - SECRET_KEY_SALT=$SECRET_KEY_SALT
    volumes:
      - ./:/usr/local/ms-authentication-mirror
    env_file: ".env"
    networks:
      - ms-authentication-mirror
    restart: always
    ports:
      - $PORT:$PORT # host:container   
volumes:
  ms-authentication-mirror:
    name: ms-authentication-mirror

networks:
  ms-authentication-mirror:
    name: ms-authentication-mirror
    driver: bridge
